// src/frontend/apps/frontend/src/app/shared/layout/main-layout.component.ts
import { Component, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthStateService } from '../../core/services/auth-state.service';
import { CoarButtonComponent, CoarIconComponent } from '@cocoar/ui';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CommonModule, RouterModule, CoarButtonComponent, CoarIconComponent],
  template: `
    <div class="layout">
      <header class="header">
        <div class="header-left">
          <a routerLink="/" class="logo">
            <coar-icon name="shield" size="lg" />
            <span class="logo-text">Cocoar Auth</span>
          </a>
        </div>

        @if (isAuthenticated()) {
          <nav class="nav">
            <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="nav-link">
              Home
            </a>
            <a routerLink="/profile" routerLinkActive="active" class="nav-link">
              Profile
            </a>
            <a routerLink="/sessions" routerLinkActive="active" class="nav-link">
              Sessions
            </a>
            <a routerLink="/privacy" routerLinkActive="active" class="nav-link">
              Privacy
            </a>
            @if (isAdmin()) {
              <a routerLink="/admin" routerLinkActive="active" class="nav-link nav-link--admin">
                Admin
              </a>
            }
          </nav>
        }

        <div class="header-right">
          @if (isAuthenticated()) {
            <div class="user-info">
              <span class="user-name">{{ displayName() }}</span>
              <coar-button
                variant="ghost"
                size="sm"
                iconStart="logout"
                (clicked)="onLogout()">
                Logout
              </coar-button>
            </div>
          } @else {
            <coar-button
              variant="primary"
              size="sm"
              routerLink="/login">
              Login
            </coar-button>
          }
        </div>
      </header>

      <main class="main">
        <router-outlet />
      </main>

      <footer class="footer">
        <p>&copy; 2026 Cocoar Auth. All rights reserved.</p>
      </footer>
    </div>
  `,
  styles: `
    .layout {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 1.5rem;
      height: 60px;
      background: var(--color-surface-primary);
      border-bottom: 1px solid var(--color-border-primary);
    }

    .header-left {
      display: flex;
      align-items: center;
    }

    .logo {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      text-decoration: none;
      color: var(--color-text-primary);
    }

    .logo-text {
      font-size: 1.25rem;
      font-weight: 600;
    }

    .nav {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .nav-link {
      padding: 0.5rem 1rem;
      border-radius: var(--radius-md);
      text-decoration: none;
      color: var(--color-text-secondary);
      font-size: 0.875rem;
      font-weight: 500;
      transition: all 0.15s ease;
    }

    .nav-link:hover {
      background: var(--color-surface-secondary);
      color: var(--color-text-primary);
    }

    .nav-link.active {
      background: var(--color-primary-subtle);
      color: var(--color-primary);
    }

    .nav-link--admin {
      color: var(--color-accent);
    }

    .nav-link--admin.active {
      background: var(--color-accent-subtle);
      color: var(--color-accent);
    }

    .header-right {
      display: flex;
      align-items: center;
    }

    .user-info {
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }

    .user-name {
      font-size: 0.875rem;
      color: var(--color-text-secondary);
    }

    .main {
      flex: 1;
      padding: 2rem;
      max-width: 1200px;
      width: 100%;
      margin: 0 auto;
    }

    .footer {
      padding: 1rem;
      text-align: center;
      border-top: 1px solid var(--color-border-primary);
      background: var(--color-surface-primary);
    }

    .footer p {
      margin: 0;
      font-size: 0.875rem;
      color: var(--color-text-tertiary);
    }
  `,
})
export class MainLayoutComponent {
  private readonly authState = inject(AuthStateService);
  private readonly router = inject(Router);

  readonly isAuthenticated = this.authState.isAuthenticated;
  readonly isAdmin = this.authState.isAdmin;
  readonly currentUser = this.authState.currentUser;

  readonly displayName = computed(() => {
    const user = this.currentUser();
    if (!user) return '';
    if (user.firstName && user.lastName) {
      return `${user.firstName} ${user.lastName}`;
    }
    return user.userName;
  });

  onLogout(): void {
    this.authState.logout('/login');
  }
}

// src/frontend-vue/apps/frontend/src/layouts/MainLayout.vue
<script setup lang="ts">
import { useRoute, useRouter, RouterView } from 'vue-router';
import { CoarSidebar, CoarMenu, CoarMenuItem, CoarMenuHeading, CoarAvatar, CoarButton } from '@cocoar/vue-ui';
import { useAuthStore } from '@/stores/auth.store';
import { useDarkMode } from '@/composables/useDarkMode';
import { useUI } from '@/composables/useUI';

const route = useRoute();
const router = useRouter();
const auth = useAuthStore();
const { isDark, toggle: toggleDark } = useDarkMode();
const ui = useUI();

function onLogout() {
  auth.logout('/login');
}
</script>

<template>
  <div class="app-layout">
    <CoarSidebar class="app-sidebar">
      <template #header>
        <div class="sidebar-header">
          <div class="sidebar-brand">
            <span class="sidebar-brand-icon">⚡</span>
            <h1 class="sidebar-logo">Cocoar Auth</h1>
          </div>
          <div class="sidebar-user">
            <CoarAvatar :name="auth.displayName || auth.currentUser?.userName || '?'" size="s" />
            <span class="sidebar-user-name">{{ auth.displayName || auth.currentUser?.userName }}</span>
          </div>
        </div>
      </template>

      <CoarMenu borderless>
        <CoarMenuHeading>Account</CoarMenuHeading>
        <CoarMenuItem
          label="Home"
          icon="home"
          :class="{ 'nav-item--active': route.path === '/' }"
          @clicked="router.push('/')"
        />
        <CoarMenuItem
          label="Profile"
          icon="user"
          :class="{ 'nav-item--active': route.path === '/profile' }"
          @clicked="router.push('/profile')"
        />
        <CoarMenuItem
          label="Sessions"
          icon="monitor"
          :class="{ 'nav-item--active': route.path === '/sessions' }"
          @clicked="router.push('/sessions')"
        />
        <CoarMenuItem
          label="Privacy"
          icon="shield"
          :class="{ 'nav-item--active': route.path === '/privacy' }"
          @clicked="router.push('/privacy')"
        />

        <template v-if="auth.isAdmin">
          <CoarMenuHeading>Administration</CoarMenuHeading>
          <CoarMenuItem
            label="Users"
            icon="users"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/users') }"
            @clicked="router.push('/admin/users')"
          />
          <CoarMenuItem
            label="Roles"
            icon="shield-check"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/roles') }"
            @clicked="router.push('/admin/roles')"
          />
          <CoarMenuItem
            label="Clients"
            icon="key-round"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/oauth/clients') }"
            @clicked="router.push('/admin/oauth/clients')"
          />
          <CoarMenuItem
            label="Scopes"
            icon="scan-line"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/oauth/scopes') }"
            @clicked="router.push('/admin/oauth/scopes')"
          />
          <CoarMenuItem
            label="API Resources"
            icon="server"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/oauth/api-resources') }"
            @clicked="router.push('/admin/oauth/api-resources')"
          />
          <CoarMenuItem
            label="Login Providers"
            icon="lock"
            :class="{ 'nav-item--active': route.path.startsWith('/admin/login-providers') }"
            @clicked="router.push('/admin/login-providers')"
          />
        </template>
      </CoarMenu>

      <template #footer>
        <div class="sidebar-footer">
          <CoarMenu borderless>
            <CoarMenuItem
              :label="isDark ? 'Light Mode' : 'Dark Mode'"
              :icon="isDark ? 'sun' : 'moon'"
              @clicked="toggleDark"
            />
            <CoarMenuItem
              label="Sign Out"
              icon="log-out"
              @clicked="onLogout"
            />
          </CoarMenu>
        </div>
      </template>
    </CoarSidebar>

    <div class="main-wrapper">
      <header v-if="ui.state.header.show && ui.state.header.title" class="page-header">
        <div class="page-container">
          <div class="page-header-titles">
            <h1 class="page-title">{{ ui.state.header.title }}</h1>
            <p v-if="ui.state.header.subTitle" class="page-subtitle">{{ ui.state.header.subTitle }}</p>
          </div>
        </div>
      </header>
      <div v-if="ui.state.content.showLoadingBar" class="loading-bar">
        <div class="loading-bar-progress" />
      </div>
      <main class="main-content" :class="{ 'main-content--scrollable': ui.state.content.scrollable, 'main-content--padded': ui.state.content.padding }">
        <div v-if="ui.state.content.container" class="page-container page-container--content">
          <RouterView />
        </div>
        <div v-else class="page-fullwidth">
          <RouterView />
        </div>
      </main>
      <footer v-if="ui.state.footer.show" class="page-footer">
        <div class="page-container page-footer-inner">
          <CoarButton
            v-if="ui.state.footer.button1.visible"
            variant="secondary"
            :disabled="ui.state.footer.button1.disabled"
            :loading="ui.state.footer.button1.loading"
            @click="ui.state.footer.button1.onClick?.()"
          >
            {{ ui.state.footer.button1.text }}
          </CoarButton>
          <div class="footer-spacer" />
          <CoarButton
            v-if="ui.state.footer.button2.visible"
            variant="danger"
            :disabled="ui.state.footer.button2.disabled"
            :loading="ui.state.footer.button2.loading"
            @click="ui.state.footer.button2.onClick?.()"
          >
            {{ ui.state.footer.button2.text }}
          </CoarButton>
          <CoarButton
            v-if="ui.state.footer.button3.visible"
            variant="primary"
            :disabled="ui.state.footer.button3.disabled"
            :loading="ui.state.footer.button3.loading"
            @click="ui.state.footer.button3.onClick?.()"
          >
            {{ ui.state.footer.button3.text }}
          </CoarButton>
        </div>
      </footer>
    </div>
  </div>
</template>

<style scoped>
.app-layout {
  display: flex;
  min-height: 100vh;
  max-height: 100vh;
  overflow: hidden;
}

.app-sidebar {
  width: 260px;
  min-width: 260px;
  height: 100vh;
  --coar-sidebar-background: var(--coar-background-neutral-secondary);
  --coar-sidebar-border: none;
  box-shadow: var(--coar-shadow-right);
  position: relative;
  z-index: 10;
}

.sidebar-header {
  padding: 1.25rem 1.25rem 1rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.sidebar-brand {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.sidebar-brand-icon {
  font-size: 1.25rem;
  line-height: 1;
}

.sidebar-logo {
  margin: 0;
  font-size: 0.9375rem;
  font-weight: 700;
  color: var(--coar-text-neutral-primary);
  letter-spacing: -0.01em;
}

.sidebar-user {
  display: flex;
  align-items: center;
  gap: 0.625rem;
  padding: 0.5rem 0.25rem;
  border-top: 1px solid var(--coar-border-neutral-tertiary, #e2e8f0);
  padding-top: 0.875rem;
}

.sidebar-user-name {
  font-size: 0.8125rem;
  font-weight: 500;
  color: var(--coar-text-neutral-secondary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.sidebar-footer {
  padding: 0.375rem 0.75rem 0.75rem;
}

.main-wrapper {
  flex: 1;
  background: var(--coar-background-neutral-primary);
  height: 100vh;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

/* Shared centered container */
.page-container {
  width: 85%;
  max-width: 1200px;
  margin: 0 auto;
}

.page-container--content {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.page-fullwidth {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 0 1.5rem;
}

/* Header - fixed 64px height */
.page-header {
  height: 64px;
  display: flex;
  align-items: center;
  border-bottom: 1px solid var(--coar-border-neutral-tertiary, #e2e8f0);
  flex-shrink: 0;
}

.page-header-titles {
  min-width: 0;
}

.page-title {
  margin: 0;
  font-size: 1.25rem;
  font-weight: 700;
  color: var(--coar-text-neutral-primary);
  letter-spacing: -0.02em;
  line-height: 1.2;
}

.page-subtitle {
  margin: 0.125rem 0 0;
  font-size: 0.8125rem;
  color: var(--coar-text-neutral-secondary);
  line-height: 1.2;
}

.loading-bar {
  height: 3px;
  background: var(--coar-background-neutral-secondary);
  overflow: hidden;
  flex-shrink: 0;
}

.loading-bar-progress {
  height: 100%;
  width: 30%;
  background: var(--coar-text-accent-primary);
  animation: loading-slide 1.5s ease-in-out infinite;
}

@keyframes loading-slide {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(400%); }
}

.main-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
  overflow: hidden;
}

.main-content--scrollable {
  overflow-y: auto;
}

.main-content--padded {
  padding-top: 1.5rem;
  padding-bottom: 1.5rem;
}

/* Footer - fixed 64px height */
.page-footer {
  height: 64px;
  display: flex;
  align-items: center;
  border-top: 1px solid var(--coar-border-neutral-tertiary, #e2e8f0);
  flex-shrink: 0;
}

.page-footer-inner {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.footer-spacer {
  flex: 1;
}
</style>

<style>
/* Active nav item — same pattern as Showcase */
.nav-item--active {
  background: var(--coar-background-accent-tertiary) !important;
  color: var(--coar-text-accent-primary) !important;
}

.nav-item--active .coar-menu-item__label {
  color: var(--coar-text-accent-primary) !important;
  font-weight: var(--coar-body-base-bold-weight) !important;
}
</style>
